services:
  - type: web
    name: imforwarder
    runtime: docker
    plan: free
    repo: https://github.com/Testinfd/imforwarder.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py & python app.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DB_NAME
        value: telegram_downloader
      - key: FREEMIUM_LIMIT
        value: "0"
      - key: PREMIUM_LIMIT
        value: "500" 