services:
  - type: web
    name: imforwarder
    runtime: docker
    plan: free
    repo: https://github.com/Testinfd/imforwarder.git
    branch: main
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING
        sync: false
      - key: LOG_GROUP
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: DB_NAME
        value: telegram_downloader
      - key: FREEMIUM_LIMIT
        value: "100000"
      - key: PREMIUM_LIMIT
        value: "100000" 